# Generated by Django 4.1.2 on 2022-10-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
    ]
